# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating_id',
            new_name='rating',
        ),
    ]
