# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0002_userratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratings',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='userratings',
            name='movie',
            field=models.OneToOneField(default=999999, on_delete=django.db.models.deletion.CASCADE, to='api_root.Movie'),
            preserve_default=False,
        ),
    ]
