# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0003_movieratings_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieratings',
            name='imdb_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movieratings',
            name='movie_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
