# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0003_auto_20170411_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_root.Movie'),
        ),
    ]
