# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0007_movieratings_rating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieratings',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieratings',
            name='rating_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
