# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0008_auto_20170325_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieratings',
            name='movie_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_root.Movie'),
            preserve_default=False,
        ),
    ]
