# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_root', '0009_auto_20170325_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieratings',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
